config/routes.rb
Rails.application.routes.draw do
    # get 'users/show' <== マイページを作成するための削除した。第5章。
  root to: 'homes#top'  #トップページへ
  devise_for :users     # deviseを使用する際にURLとしてusersを含むことを示している 20210213
    # resourcesメソッドは、ルーティングを一括して自動生成してくれる。20210213
    # 一方、onlyは、生成するルーティングを限定するオプションである。20210213
    # 画像投稿には、「新規投稿」「一覧」「詳細機能」「削除」しか使わないため、不要なルーティングが実行されないようにonlyを設定する。20210213

    # resources :post_images, only: [:new, :create, :index, :show, :destroy] このコードは以下のコードが実装される前のコードだ。

    # コメントは、投稿画像に対してコメントされます。このため、post_commentsは、post_imagesに結びつきます。
    # 以下のように親子関係になります。
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
      # いいね機能のルーティンング
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

    # コントローラを生成するコマンドを実行した際、routes.rbファイルにget 'users/show'というルーティングが生成される。
    # resourcesの設定と重複を避けるために既存のget 'users/show' のルーティングを削除する。
  resources :users, only: [:show, :edit, :update]   # onlyを使って、不必要なルーティングが生成されるのを制限しよう。
                                                    # 編集ページのeditアクション用のルーティングを追加する。
                                                    # 編集データの保存機能のupdataアクション用のルーティングを追加する。

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_image.rb
class PostImage < ApplicationRecord

  # PostImageモデルに対して、Userモデルとの関係性を追加していく。20210214
  # belongs_toは、PostImageモデルからuser_idに関連付けられていて、Userモデルを参照することができる。20210214
  # PostImageモデルに関連付けられるのは、1つのUserモデルである。このため、単数形の「user」になっている点に注意しよう。20210214
  belongs_to :user  # ==>第3章で設定した。

  # モデルに、画像アップ用のメソッド（attachment）を追加してフィールド名に（image）を指定する。refileを使用するうえでのルールだ。
  attachment :image

  # PostImageモデルに、PostCommentモデルとの関連付けを追加する。==>第4章で設定した。
  has_many :post_comments, dependent: :destroy

  # いいね機能を搭載するための設定、PostImageモデルに関連付けを追加する
  has_many :favorites, dependent: :destroy

  validates :shop_name, presence: true    # 画像投稿に対して「必須入力」の設定が必要なので、PostImageモデルにデータ保存の記述を追加する。presence（存在）
  validates :image, presence: true


  def favorited_by?(user)  # favorited_by?メソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる。存在していればtrue、存在していなければfalseを返すようにしている。
    favorites.where(user_id: user.id).exists?
  end


end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new  # 画像投稿の画面を表示するアクションメソッド
    @post_image = PostImage.new   # インスタンス変数に空のインスタンスを渡して、画像の投稿ができるようにする。
  end

  # 投稿データの保存
  def create  # 投稿データを保存するアクションメソッド
    @post_image = PostImage.new(post_image_params) # post_image_paramsでは、フォームで入力されたデータが投稿データとして許可されているパラメータかどうかをチェックしている。
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path # PostImageモデルに保存した後、リダイレクトで投稿一覧画面へ戻る。
    else
      render :new  # falseならば、画像投稿ページを再表示するように設定する。　renderはサーバーを通さずに直接行きたいページ(今回は画像投稿ページnew)へ送られる
    end
  end

  # 投稿一覧画面
  def index # 投稿された画像が一覧で表示されるようにする。
    # @post_images = PostImage.all # タイムライン上に表示する投稿データを取得できるようになる。

    # 下記のコードは上記のコメント内のコードに、1ページ分の決められた数のデータだけを、新しい順に取得するように変更している。
    # pageメソッドは、kaminariをインストールしたことで使用可能になったメソッドだ。
    @post_images = PostImage.page(params[:page]).reverse_order
  end

  # 投稿画像の詳細ページを設定する。
  def show # 詳細画面が表示されるように設定する。
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new  # コメントのインスタンス変数を記述する。
  end

  # 投稿を削除できるようにする。
  def destroy # 投稿の削除後は一覧に遷移するようにする。
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end


  # 投稿データを保存するためには、Strong Parametersも必要なので、同時に(createメソッドを)定義していきます。
  # 投稿データのストロングパラメータ
  private

  def post_image_params   # post_image_paramsでは、フォームで入力されたデータが投稿データとして許可されているパラメータかどうかをチェックしている。
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/_list.html.erb
<div class="card-list-containar py-5">
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %> ｜ </span>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<!-- 部分テンプレートに必要な共通化をするためにここにあったコードを切り取って[_list.html.erbファイル(共通化ファイル)]へ貼り付けた。第7章-->

<!--他ページにもプロフィール画像を反映させる-->
<!--[変更前] < %= image_tag('sample-author1.jpg') %> -->
<!--[変更後] < %= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %> -->

<!---->
<!--[変更前] < %= image_tag('sample-author1.jpg') %> -->
<!--[変更後] < %= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %> -->


<!--post_images/index.html.erbから呼び出す-->
<%= render 'post_images/list', post_images: @post_images %>
<!--< %= render [部分テンプレートファイルの指定], [ローカル変数]:[渡す値] %>-->

app/views/post_images/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
      <div class="form-body p-4">
        <% if @post_image.errors.any? %>
          <%= @post_image.errors.count %>件のエラーが発生しました
          <% @post_image.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= form_with model: @post_image, local:true do |f| %>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-building"></i></span>
            </div>
            <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
          </div>
          <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
          <hr>
          <%= f.submit '投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="post-body">
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名：<%= @post_image.shop_name %></p>
  <p>説明：<%= @post_image.caption %></p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p> <!-- 投稿日付の形式を変換しているメソッドで、'%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換する。 -->
  <% if @post_image.user == current_user %> <!--もし、投稿者 == 現在ログインしているユーザ だったら-->
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>  <!--削除ボタン-->
  <% end %>  <!--終わり-->
</div>

  <!-- いいね機能搭載 -->
  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  <!-- ここまで -->


<!-- 投稿画像の詳細画面で、コメントを投稿できるようにする。また、投稿画像へのコメント、コメント数も表示させる。-->
<div class="comments">
  <p>コメント件数：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
    <p><%= image_tag('sample-author1.jpg') %></p>
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% end %>
</div>
<div class="new-comment">
  <%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>  <!-- インスタンス変数が2つあることに注意する。コメントは、post_imageに結びついたpost_commentにあるため、2つ用意する必要がある。また、post_commentをcreateするためのリクエストは、ルーティングもネスト（親子関係）しているため、上記2つの情報が必要になる。-->
    <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>
<!--ここまで-->