config/routes.rb
Rails.application.routes.draw do
    # get 'users/show' <== マイページを作成するための削除した。第5章。
  root to: 'homes#top'  #トップページへ
  devise_for :users     # deviseを使用する際にURLとしてusersを含むことを示している 20210213
    # resourcesメソッドは、ルーティングを一括して自動生成してくれる。20210213
    # 一方、onlyは、生成するルーティングを限定するオプションである。20210213
    # 画像投稿には、「新規投稿」「一覧」「詳細機能」「削除」しか使わないため、不要なルーティングが実行されないようにonlyを設定する。20210213

    # resources :post_images, only: [:new, :create, :index, :show, :destroy] このコードは以下のコードが実装される前のコードだ。

    # コメントは、投稿画像に対してコメントされます。このため、post_commentsは、post_imagesに結びつきます。
    # 以下のように親子関係になります。
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
      # いいね機能のルーティンング
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

    # コントローラを生成するコマンドを実行した際、routes.rbファイルにget 'users/show'というルーティングが生成される。
    # resourcesの設定と重複を避けるために既存のget 'users/show' のルーティングを削除する。
  resources :users, only: [:show, :edit, :update]   # onlyを使って、不必要なルーティングが生成されるのを制限しよう。
                                                    # 編集ページのeditアクション用のルーティングを追加する。
                                                    # 編集データの保存機能のupdataアクション用のルーティングを追加する。

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Bootstrapを導入後のヘッダー・フッターを整える作業~ここから~-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--Bootstrapを導入後のヘッダー・フッターを整える作業~ここまで~-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--第9章のヘッダー・フッターを整えようの部分で編集した~ここから~-->
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿フォーム', new_post_image_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>善良な市民同士で無差別に食欲を煽るSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
  <!--第9章のヘッダー・フッターを整えようの部分で編集した~ここまで~-->
</html>